[workspace]
exclude = [
  "examples/attachments",
]
members = [
  "core",
  "gpu",
  "painter",
  "macros",
  "macros/builtin",
  "algo",
  "text",
  "widgets",
  "ribir",
  "themes/material",
  "geom",
  "tests",
  "dev-helper",
  "examples/*",
]
resolver = "2"

[profile.bench]
debug = true

[profile.release]
debug = true

[workspace.package]
authors = ["RibirX<Adoo@outlook.com>"]
categories = ["gui"]
description = "Ribir is a framework for building modern native/wasm cross-platform user interface applications."
documentation = "https://ribir.org/docs"
edition = "2021"
homepage = "https://ribir.org"
keywords = ["gui", "ui", "declarative", "compose-ui"]
license = "MIT"
readme = "README.md"
version = "0.0.1-alpha.4"

[workspace.dependencies]
Inflector = "0.11.4"
ahash = "0.8.3"
arboard = "3.2.0"
bitflags = "2.0.0"
blake3 = "1.3.3"
colored = "2.0.0"
derive_more = "0.99.17"
dssim-core = "3.2.6"
env_logger = "0.7.1"
euclid = "0.22.6"
fontdb = "0.14.1"
futures = "0.3.26"
guillotiere = "0.6.0"
image = {version = "0.24.5", default-features = false}
indextree = "4.5.0"
lazy_static = "1.4.0"
log = "0.4.14"
lyon_algorithms = "1.0.1"
lyon_geom = "1.0.1"
lyon_path = "1.0.1"
lyon_tessellation = "1.0.1"
material-color-utilities-rs = "0.2.1"
icrate = "0.0.4"
once_cell = "1.17.1"
ordered-float = "3.4.0"
paste = "1.0"
pin-project-lite = "0.2.9"
proc-macro2 = "1.0.36"
quote = "1.0.16"
raw-window-handle = "0.5.0"
rayon = "1.5.1"
rctree = "0.5.0"
rustybuzz = "0.8.0"
rxrust = {version = "1.0.0-beta.4", default-features = false, features = ["futures-scheduler"]}
scoped_threadpool = "0.1.9"
serde = "1.0"
serde_json = "1.0.82"
smallvec = "1.8.0"
syn = "1.0.109"
tiny-skia-path = {version = "0.11.0"}
unicode-bidi = "0.3.7"
unicode-script = "0.5.4"
unicode-segmentation = "1.9.0"
usvg = { version= "0.35.0", default-features = false }
webbrowser = "0.8.8"
wgpu = {version = "0.16.0"}
winit = {version = "0.28.5", default-features = false, features = ["x11", "wayland", "wayland-dlopen"]}
zerocopy = "0.7.3"
quick-xml = "0.30.0"

[workspace.metadata.release]
shared-version = true
tag = false
