[package]
authors.workspace = true
categories.workspace = true
description.workspace = true
documentation.workspace = true
edition.workspace = true
homepage.workspace = true
keywords.workspace = true
license.workspace = true
name = "ribir"
readme.workspace = true
repository = "https://github.com/RibirX/Ribir/ribir"
version.workspace = true

[dependencies]
arboard = "3.2.0"
once_cell.workspace = true
ribir_core = {path = "../core", version = "0.0.1-alpha.4"}
ribir_gpu = {path = "../gpu", version = "0.0.1-alpha.4"}
ribir_material = {path = "../themes/material", version = "0.0.1-alpha.4", optional = true}
ribir_widgets = {path = "../widgets", version = "0.0.1-alpha.4", optional = true}
rxrust.workspace = true
wgpu = {workspace = true, optional = true}
winit.workspace = true
[target.'cfg(target_os = "macos")'.dependencies]
icrate = {workspace = true, features = ["Foundation", "Foundation_NSAppleEventManager", "objective-c", "AppKit", "AppKit_NSEvent"]}

[dev-dependencies]
colored.workspace = true
env_logger.workspace = true
futures.workspace = true
ribir_dev_helper = {path = "../dev-helper"}
ribir_material = {path = "../themes/material"}

[features]
default = ["wgpu", "widgets", "material"]
material = ["ribir_material"]
png = ["ribir_core/png"]
wgpu = ["ribir_gpu/wgpu", "dep:wgpu"]
widgets = ["ribir_widgets"]

[[test]]
harness = false
name = "single_thread"
path = "tests/timer_test.rs"

[target.'cfg(windows)'.dependencies]
winapi = "0.3.9"

[package.metadata.release]
tag = true
